name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # Use the version of Go you require

      - name: Install dependencies
        run: echo "go mod tidy"

      - name: Run tests
        run: |
          echo "running: go test ./... -v"

      - name: Build the Go app
        run: echo "go build -o build/myapp"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        if: success()
        run: |
          echo "Deploying to production"
